apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: torchani

resources:
  - ../../base/torchani-service

patchesStrategicMerge:
  - deployment-patch.yaml
  - hpa-patch.yaml

configMapGenerator:
  - name: torchani-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - MODEL_MAX_LOADED=3
      - GPU_MEMORY_LIMIT=0.85

replicas:
  - name: torchani-api
    count: 2
  - name: celery-worker
    count: 2

images:
  - name: torchani-service
    newName: ghcr.io/Ameyanagi/torchani-service
    newTag: latest  # Will be updated by CI/CD
  - name: torchani-service-celery
    newName: ghcr.io/Ameyanagi/torchani-service
    newTag: latest-celery