apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - redis.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: torchani-service
  app.kubernetes.io/part-of: cheminfuse
  app.kubernetes.io/managed-by: argocd

configMapGenerator:
  - name: torchani-config
    behavior: merge
    literals:
      - ENVIRONMENT=production

secretGenerator:
  - name: torchani-secrets
    type: Opaque
    literals:
      - redis-password=changeme  # This should be replaced with sealed-secrets